/*
 * WARNING: do not edit!
 * Generated by buildinf.h.cmake
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define CFLAGS "compiler: @CMAKE_C_COMPILER_ID@ @CMAKE_C_FLAGS@"
#define PLATFORM "platform: @CMAKE_SYSTEM_NAME@"
#define DATE "built on: @BUILDINF_DATE@"
static const char *compiler_flags = CFLAGS;

